connection: "mock_trial_thelook"

include: "/views/*.view.lkml"

explore: order_items_pop {
  label: "Order Items with PoP"
  join: pop_support {
    type: cross
    relationship: one_to_one
  }
  # You might want to add a sql_always_where to filter out future dates
  # that can be generated by the pop_date logic, for example:
  # sql_always_where: ${pop_support.pop_date_date} <= current_date() ;;
}
